//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveClient.PuzzleManagerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuzzleInfoDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.P" +
        "uzzle")]
    [System.SerializableAttribute()]
    public partial class PuzzleInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUploadedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuzzleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageBytes {
            get {
                return this.ImageBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageBytesField, value) != true)) {
                    this.ImageBytesField = value;
                    this.RaisePropertyChanged("ImageBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUploaded {
            get {
                return this.IsUploadedField;
            }
            set {
                if ((this.IsUploadedField.Equals(value) != true)) {
                    this.IsUploadedField = value;
                    this.RaisePropertyChanged("IsUploaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuzzleId {
            get {
                return this.PuzzleIdField;
            }
            set {
                if ((this.PuzzleIdField.Equals(value) != true)) {
                    this.PuzzleIdField = value;
                    this.RaisePropertyChanged("PuzzleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
        "hared")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.PuzzleManagerService.ServiceErrorType ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.PuzzleManagerService.ServiceErrorType ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
        "hared")]
    public enum ServiceErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
        "hared")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MindWeaveClient.PuzzleManagerService.UploadResultDto))]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.P" +
        "uzzle")]
    [System.SerializableAttribute()]
    public partial class UploadResultDto : MindWeaveClient.PuzzleManagerService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewPuzzleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewPuzzleId {
            get {
                return this.NewPuzzleIdField;
            }
            set {
                if ((this.NewPuzzleIdField.Equals(value) != true)) {
                    this.NewPuzzleIdField = value;
                    this.RaisePropertyChanged("NewPuzzleId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuzzleDefinitionDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.P" +
        "uzzle")]
    [System.SerializableAttribute()]
    public partial class PuzzleDefinitionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FullImageBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.PuzzleManagerService.PuzzlePieceDefinitionDto[] PiecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuzzleHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuzzleWidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FullImageBytes {
            get {
                return this.FullImageBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.FullImageBytesField, value) != true)) {
                    this.FullImageBytesField = value;
                    this.RaisePropertyChanged("FullImageBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.PuzzleManagerService.PuzzlePieceDefinitionDto[] Pieces {
            get {
                return this.PiecesField;
            }
            set {
                if ((object.ReferenceEquals(this.PiecesField, value) != true)) {
                    this.PiecesField = value;
                    this.RaisePropertyChanged("Pieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuzzleHeight {
            get {
                return this.PuzzleHeightField;
            }
            set {
                if ((this.PuzzleHeightField.Equals(value) != true)) {
                    this.PuzzleHeightField = value;
                    this.RaisePropertyChanged("PuzzleHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuzzleWidth {
            get {
                return this.PuzzleWidthField;
            }
            set {
                if ((this.PuzzleWidthField.Equals(value) != true)) {
                    this.PuzzleWidthField = value;
                    this.RaisePropertyChanged("PuzzleWidth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuzzlePieceDefinitionDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.P" +
        "uzzle")]
    [System.SerializableAttribute()]
    public partial class PuzzlePieceDefinitionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BottomNeighborIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CorrectXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CorrectYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitialXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitialYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LeftNeighborIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PieceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RightNeighborIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TopNeighborIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BottomNeighborId {
            get {
                return this.BottomNeighborIdField;
            }
            set {
                if ((this.BottomNeighborIdField.Equals(value) != true)) {
                    this.BottomNeighborIdField = value;
                    this.RaisePropertyChanged("BottomNeighborId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CorrectX {
            get {
                return this.CorrectXField;
            }
            set {
                if ((this.CorrectXField.Equals(value) != true)) {
                    this.CorrectXField = value;
                    this.RaisePropertyChanged("CorrectX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CorrectY {
            get {
                return this.CorrectYField;
            }
            set {
                if ((this.CorrectYField.Equals(value) != true)) {
                    this.CorrectYField = value;
                    this.RaisePropertyChanged("CorrectY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialX {
            get {
                return this.InitialXField;
            }
            set {
                if ((this.InitialXField.Equals(value) != true)) {
                    this.InitialXField = value;
                    this.RaisePropertyChanged("InitialX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialY {
            get {
                return this.InitialYField;
            }
            set {
                if ((this.InitialYField.Equals(value) != true)) {
                    this.InitialYField = value;
                    this.RaisePropertyChanged("InitialY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LeftNeighborId {
            get {
                return this.LeftNeighborIdField;
            }
            set {
                if ((this.LeftNeighborIdField.Equals(value) != true)) {
                    this.LeftNeighborIdField = value;
                    this.RaisePropertyChanged("LeftNeighborId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PieceId {
            get {
                return this.PieceIdField;
            }
            set {
                if ((this.PieceIdField.Equals(value) != true)) {
                    this.PieceIdField = value;
                    this.RaisePropertyChanged("PieceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RightNeighborId {
            get {
                return this.RightNeighborIdField;
            }
            set {
                if ((this.RightNeighborIdField.Equals(value) != true)) {
                    this.RightNeighborIdField = value;
                    this.RaisePropertyChanged("RightNeighborId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceX {
            get {
                return this.SourceXField;
            }
            set {
                if ((this.SourceXField.Equals(value) != true)) {
                    this.SourceXField = value;
                    this.RaisePropertyChanged("SourceX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceY {
            get {
                return this.SourceYField;
            }
            set {
                if ((this.SourceYField.Equals(value) != true)) {
                    this.SourceYField = value;
                    this.RaisePropertyChanged("SourceY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TopNeighborId {
            get {
                return this.TopNeighborIdField;
            }
            set {
                if ((this.TopNeighborIdField.Equals(value) != true)) {
                    this.TopNeighborIdField = value;
                    this.RaisePropertyChanged("TopNeighborId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PuzzleManagerService.IPuzzleManager")]
    public interface IPuzzleManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPuzzleManager/getAvailablePuzzles", ReplyAction="http://tempuri.org/IPuzzleManager/getAvailablePuzzlesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MindWeaveClient.PuzzleManagerService.ServiceFaultDto), Action="http://tempuri.org/IPuzzleManager/getAvailablePuzzlesServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
            "hared")]
        MindWeaveClient.PuzzleManagerService.PuzzleInfoDto[] getAvailablePuzzles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPuzzleManager/getAvailablePuzzles", ReplyAction="http://tempuri.org/IPuzzleManager/getAvailablePuzzlesResponse")]
        System.Threading.Tasks.Task<MindWeaveClient.PuzzleManagerService.PuzzleInfoDto[]> getAvailablePuzzlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPuzzleManager/uploadPuzzleImage", ReplyAction="http://tempuri.org/IPuzzleManager/uploadPuzzleImageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MindWeaveClient.PuzzleManagerService.ServiceFaultDto), Action="http://tempuri.org/IPuzzleManager/uploadPuzzleImageServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
            "hared")]
        MindWeaveClient.PuzzleManagerService.UploadResultDto uploadPuzzleImage(string username, byte[] imageBytes, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPuzzleManager/uploadPuzzleImage", ReplyAction="http://tempuri.org/IPuzzleManager/uploadPuzzleImageResponse")]
        System.Threading.Tasks.Task<MindWeaveClient.PuzzleManagerService.UploadResultDto> uploadPuzzleImageAsync(string username, byte[] imageBytes, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPuzzleManager/getPuzzleDefinition", ReplyAction="http://tempuri.org/IPuzzleManager/getPuzzleDefinitionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MindWeaveClient.PuzzleManagerService.ServiceFaultDto), Action="http://tempuri.org/IPuzzleManager/getPuzzleDefinitionServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
            "hared")]
        MindWeaveClient.PuzzleManagerService.PuzzleDefinitionDto getPuzzleDefinition(int puzzleId, int difficultyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPuzzleManager/getPuzzleDefinition", ReplyAction="http://tempuri.org/IPuzzleManager/getPuzzleDefinitionResponse")]
        System.Threading.Tasks.Task<MindWeaveClient.PuzzleManagerService.PuzzleDefinitionDto> getPuzzleDefinitionAsync(int puzzleId, int difficultyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPuzzleManagerChannel : MindWeaveClient.PuzzleManagerService.IPuzzleManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PuzzleManagerClient : System.ServiceModel.ClientBase<MindWeaveClient.PuzzleManagerService.IPuzzleManager>, MindWeaveClient.PuzzleManagerService.IPuzzleManager {
        
        public PuzzleManagerClient() {
        }
        
        public PuzzleManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PuzzleManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PuzzleManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PuzzleManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MindWeaveClient.PuzzleManagerService.PuzzleInfoDto[] getAvailablePuzzles() {
            return base.Channel.getAvailablePuzzles();
        }
        
        public System.Threading.Tasks.Task<MindWeaveClient.PuzzleManagerService.PuzzleInfoDto[]> getAvailablePuzzlesAsync() {
            return base.Channel.getAvailablePuzzlesAsync();
        }
        
        public MindWeaveClient.PuzzleManagerService.UploadResultDto uploadPuzzleImage(string username, byte[] imageBytes, string fileName) {
            return base.Channel.uploadPuzzleImage(username, imageBytes, fileName);
        }
        
        public System.Threading.Tasks.Task<MindWeaveClient.PuzzleManagerService.UploadResultDto> uploadPuzzleImageAsync(string username, byte[] imageBytes, string fileName) {
            return base.Channel.uploadPuzzleImageAsync(username, imageBytes, fileName);
        }
        
        public MindWeaveClient.PuzzleManagerService.PuzzleDefinitionDto getPuzzleDefinition(int puzzleId, int difficultyId) {
            return base.Channel.getPuzzleDefinition(puzzleId, difficultyId);
        }
        
        public System.Threading.Tasks.Task<MindWeaveClient.PuzzleManagerService.PuzzleDefinitionDto> getPuzzleDefinitionAsync(int puzzleId, int difficultyId) {
            return base.Channel.getPuzzleDefinitionAsync(puzzleId, difficultyId);
        }
    }
}
