//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveClient.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindWeaveClient.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Victory.
        /// </summary>
        public static string AchievementFirstVictory {
            get {
                return ResourceManager.GetString("AchievementFirstVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hardcore Gamer.
        /// </summary>
        public static string AchievementHardcoreGamer {
            get {
                return ResourceManager.GetString("AchievementHardcoreGamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High Scorer.
        /// </summary>
        public static string AchievementHighScorer {
            get {
                return ResourceManager.GetString("AchievementHighScorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host with the Most.
        /// </summary>
        public static string AchievementHostWithTheMost {
            get {
                return ResourceManager.GetString("AchievementHostWithTheMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Just Beginning.
        /// </summary>
        public static string AchievementJustBeginning {
            get {
                return ResourceManager.GetString("AchievementJustBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Novice Weaver.
        /// </summary>
        public static string AchievementNoviceWeaver {
            get {
                return ResourceManager.GetString("AchievementNoviceWeaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participation Award.
        /// </summary>
        public static string AchievementParticipationAward {
            get {
                return ResourceManager.GetString("AchievementParticipationAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piece Collector.
        /// </summary>
        public static string AchievementPieceCollector {
            get {
                return ResourceManager.GetString("AchievementPieceCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puzzle Master.
        /// </summary>
        public static string AchievementPuzzleMaster {
            get {
                return ResourceManager.GetString("AchievementPuzzleMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed Demon.
        /// </summary>
        public static string AchievementSpeedDemon {
            get {
                return ResourceManager.GetString("AchievementSpeedDemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject Zero.
        /// </summary>
        public static string AchievementSubjectZero {
            get {
                return ResourceManager.GetString("AchievementSubjectZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time Warp.
        /// </summary>
        public static string AchievementTimeWarp {
            get {
                return ResourceManager.GetString("AchievementTimeWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACHIEVEMENT UNLOCKED!.
        /// </summary>
        public static string AchievementUnlockedTitle {
            get {
                return ResourceManager.GetString("AchievementUnlockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot accept invitation while already in a game..
        /// </summary>
        public static string CannotAcceptInviteAlreadyInGame {
            get {
                return ResourceManager.GetString("CannotAcceptInviteAlreadyInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot connect...service..
        /// </summary>
        public static string CannotConnectMatchmaking {
            get {
                return ResourceManager.GetString("CannotConnectMatchmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to lobby chat..
        /// </summary>
        public static string ChatConnectError {
            get {
                return ResourceManager.GetString("ChatConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mind Weave\nDeveloped by:\nAldo Antonio Campos Gómez\nAngel Jonathan Puch Hernández\n\n© 2025.
        /// </summary>
        public static string CreditsContent {
            get {
                return ResourceManager.GetString("CreditsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Easy (25 Pcs).
        /// </summary>
        public static string DifficultyOptEasy {
            get {
                return ResourceManager.GetString("DifficultyOptEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hard (100 Pcs).
        /// </summary>
        public static string DifficultyOptHard {
            get {
                return ResourceManager.GetString("DifficultyOptHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium (50 Pcs).
        /// </summary>
        public static string DifficultyOptMedium {
            get {
                return ResourceManager.GetString("DifficultyOptMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Avatar.
        /// </summary>
        public static string EditProfileBtnChangeAvatar {
            get {
                return ResourceManager.GetString("EditProfileBtnChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string EditProfileBtnChangePassword {
            get {
                return ResourceManager.GetString("EditProfileBtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save changes.
        /// </summary>
        public static string EditProfileBtnSaveChanges {
            get {
                return ResourceManager.GetString("EditProfileBtnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        public static string EditProfileLbCurrentPassword {
            get {
                return ResourceManager.GetString("EditProfileLbCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error changing password..
        /// </summary>
        public static string ErrorChangingPassword {
            get {
                return ResourceManager.GetString("ErrorChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar los datos del perfil.
        /// </summary>
        public static string ErrorFailedToLoadProfile {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected file is too large for the server configuration..
        /// </summary>
        public static string ErrorFileTooBigForServer {
            get {
                return ResourceManager.GetString("ErrorFileTooBigForServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not generate a unique guest username. Please try another name..
        /// </summary>
        public static string ErrorGuestUsernameGenerationFailed {
            get {
                return ResourceManager.GetString("ErrorGuestUsernameGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image is too large. Max size is {0}MB..
        /// </summary>
        public static string ErrorImageTooLarge {
            get {
                return ResourceManager.GetString("ErrorImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid, expired, or already used lobby invitation code for this email..
        /// </summary>
        public static string ErrorInvalidOrExpiredGuestInvite {
            get {
                return ResourceManager.GetString("ErrorInvalidOrExpiredGuestInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to join the lobby..
        /// </summary>
        public static string ErrorJoiningLobby {
            get {
                return ResourceManager.GetString("ErrorJoiningLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error kicking player..
        /// </summary>
        public static string ErrorKickingPlayer {
            get {
                return ResourceManager.GetString("ErrorKickingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error leaving lobby..
        /// </summary>
        public static string ErrorLeavingLobby {
            get {
                return ResourceManager.GetString("ErrorLeavingLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading friends list..
        /// </summary>
        public static string ErrorLoadingFriends {
            get {
                return ResourceManager.GetString("ErrorLoadingFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading puzzles.
        /// </summary>
        public static string ErrorLoadingPuzzles {
            get {
                return ResourceManager.GetString("ErrorLoadingPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading friend requests..
        /// </summary>
        public static string ErrorLoadingRequests {
            get {
                return ResourceManager.GetString("ErrorLoadingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while joining the lobby..
        /// </summary>
        public static string ErrorMsgGuestJoinFailed {
            get {
                return ResourceManager.GetString("ErrorMsgGuestJoinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred while logging in..
        /// </summary>
        public static string ErrorMsgLoginFailed {
            get {
                return ResourceManager.GetString("ErrorMsgLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No details provided..
        /// </summary>
        public static string ErrorMsgNoDetails {
            get {
                return ResourceManager.GetString("ErrorMsgNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while resetting your password..
        /// </summary>
        public static string ErrorMsgPasswordResetFailed {
            get {
                return ResourceManager.GetString("ErrorMsgPasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while resending the verification code..
        /// </summary>
        public static string ErrorMsgResendCodeFailed {
            get {
                return ResourceManager.GetString("ErrorMsgResendCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The server is unavailable. Please try again later..
        /// </summary>
        public static string ErrorMsgServerOffline {
            get {
                return ResourceManager.GetString("ErrorMsgServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred while registering the account..
        /// </summary>
        public static string ErrorMsgSignUpFailed {
            get {
                return ResourceManager.GetString("ErrorMsgSignUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while verifying the account..
        /// </summary>
        public static string ErrorMsgVerifyFailed {
            get {
                return ResourceManager.GetString("ErrorMsgVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error processing file.
        /// </summary>
        public static string ErrorProcessingFile {
            get {
                return ResourceManager.GetString("ErrorProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading file.
        /// </summary>
        public static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading puzzle file bytes for ID {0}..
        /// </summary>
        public static string ErrorReadingPuzzleBytes {
            get {
                return ResourceManager.GetString("ErrorReadingPuzzleBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error removing friend..
        /// </summary>
        public static string ErrorRemovingFriend {
            get {
                return ResourceManager.GetString("ErrorRemovingFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error responding to request..
        /// </summary>
        public static string ErrorRespondingRequest {
            get {
                return ResourceManager.GetString("ErrorRespondingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error searching players..
        /// </summary>
        public static string ErrorSearchingPlayer {
            get {
                return ResourceManager.GetString("ErrorSearchingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to send the guest invitation. Please try again..
        /// </summary>
        public static string ErrorSendingGuestInvitation {
            get {
                return ResourceManager.GetString("ErrorSendingGuestInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sending friend request..
        /// </summary>
        public static string ErrorSendingRequest {
            get {
                return ResourceManager.GetString("ErrorSendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your session has expired. Cannot join lobby..
        /// </summary>
        public static string ErrorSessionExpired {
            get {
                return ResourceManager.GetString("ErrorSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details:.
        /// </summary>
        public static string ErrorTitleDetails {
            get {
                return ResourceManager.GetString("ErrorTitleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error uploading image.
        /// </summary>
        public static string ErrorUploadingImage {
            get {
                return ResourceManager.GetString("ErrorUploadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create lobby..
        /// </summary>
        public static string FailedToCreateLobby {
            get {
                return ResourceManager.GetString("FailedToCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Image.
        /// </summary>
        public static string GameBtnViewImage {
            get {
                return ResourceManager.GetString("GameBtnViewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game in progress! If you leave now, you will lose your current progress (pieces placed). Only your playtime will be saved. Exit anyway?.
        /// </summary>
        public static string GameExitConfirmMessage {
            get {
                return ResourceManager.GetString("GameExitConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandon Match?.
        /// </summary>
        public static string GameExitConfirmTitle {
            get {
                return ResourceManager.GetString("GameExitConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error starting game..
        /// </summary>
        public static string GameStartError {
            get {
                return ResourceManager.GetString("GameStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string GameTxtClose {
            get {
                return ResourceManager.GetString("GameTxtClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string GlobalBtnAddFriend {
            get {
                return ResourceManager.GetString("GlobalBtnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string GlobalBtnBack {
            get {
                return ResourceManager.GetString("GlobalBtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string GlobalBtnCancel {
            get {
                return ResourceManager.GetString("GlobalBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit Game.
        /// </summary>
        public static string GlobalBtnExit {
            get {
                return ResourceManager.GetString("GlobalBtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAY.
        /// </summary>
        public static string GlobalBtnPlay {
            get {
                return ResourceManager.GetString("GlobalBtnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string GlobalBtnSignUp {
            get {
                return ResourceManager.GetString("GlobalBtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit profile.
        /// </summary>
        public static string GlobalCommonEditProfile {
            get {
                return ResourceManager.GetString("GlobalCommonEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SETTINGS.
        /// </summary>
        public static string GlobalCommonSettings {
            get {
                return ResourceManager.GetString("GlobalCommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOCIAL.
        /// </summary>
        public static string GlobalCommonSocial {
            get {
                return ResourceManager.GetString("GlobalCommonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All fields are required..
        /// </summary>
        public static string GlobalErrorAllFieldsRequired {
            get {
                return ResourceManager.GetString("GlobalErrorAllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email format..
        /// </summary>
        public static string GlobalErrorInvalidEmailFormat {
            get {
                return ResourceManager.GetString("GlobalErrorInvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit Mind Weave?.
        /// </summary>
        public static string GlobalExitConfirmMessage {
            get {
                return ResourceManager.GetString("GlobalExitConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit Mind Weave.
        /// </summary>
        public static string GlobalExitConfirmTitle {
            get {
                return ResourceManager.GetString("GlobalExitConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth.
        /// </summary>
        public static string GlobalLbBirth {
            get {
                return ResourceManager.GetString("GlobalLbBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string GlobalLbEmail {
            get {
                return ResourceManager.GetString("GlobalLbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        public static string GlobalLbFirstName {
            get {
                return ResourceManager.GetString("GlobalLbFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mind Weave.
        /// </summary>
        public static string GlobalLbGameName {
            get {
                return ResourceManager.GetString("GlobalLbGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        public static string GlobalLbGender {
            get {
                return ResourceManager.GetString("GlobalLbGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string GlobalLbLastName {
            get {
                return ResourceManager.GetString("GlobalLbLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string GlobalLbLoading {
            get {
                return ResourceManager.GetString("GlobalLbLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not specified.
        /// </summary>
        public static string GlobalLbNotSpecified {
            get {
                return ResourceManager.GetString("GlobalLbNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password recovery.
        /// </summary>
        public static string GlobalLbPasswordRecovery {
            get {
                return ResourceManager.GetString("GlobalLbPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string GlobalLbUsername {
            get {
                return ResourceManager.GetString("GlobalLbUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing....
        /// </summary>
        public static string GlobalProcessing {
            get {
                return ResourceManager.GetString("GlobalProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string GlobalTxtNewPassword {
            get {
                return ResourceManager.GetString("GlobalTxtNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid or expired verification code..
        /// </summary>
        public static string GlobalVerificationInvalidOrExpiredCode {
            get {
                return ResourceManager.GetString("GlobalVerificationInvalidOrExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Invite.
        /// </summary>
        public static string GuestInviteBtnSend {
            get {
                return ResourceManager.GetString("GuestInviteBtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sending guest invitation..
        /// </summary>
        public static string GuestInviteError {
            get {
                return ResourceManager.GetString("GuestInviteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the email address of the guest you want to invite:.
        /// </summary>
        public static string GuestInvitePromptMessage {
            get {
                return ResourceManager.GetString("GuestInvitePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Guest by Email.
        /// </summary>
        public static string GuestInvitePromptTitle {
            get {
                return ResourceManager.GetString("GuestInvitePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Lobby.
        /// </summary>
        public static string GuestJoinBtnJoin {
            get {
                return ResourceManager.GetString("GuestJoinBtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the lobby code and your email (where you received the invite)..
        /// </summary>
        public static string GuestJoinInfo {
            get {
                return ResourceManager.GetString("GuestJoinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desired Username.
        /// </summary>
        public static string GuestJoinLbDesiredUsername {
            get {
                return ResourceManager.GetString("GuestJoinLbDesiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby Code.
        /// </summary>
        public static string GuestJoinLbLobbyCode {
            get {
                return ResourceManager.GetString("GuestJoinLbLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join as Guest.
        /// </summary>
        public static string GuestJoinTitle {
            get {
                return ResourceManager.GetString("GuestJoinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest username must be 3-16 alphanumeric characters..
        /// </summary>
        public static string GuestUsernameValidationError {
            get {
                return ResourceManager.GetString("GuestUsernameValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code sent successfully.
        /// </summary>
        public static string InfoMsgBodyCodeSent {
            get {
                return ResourceManager.GetString("InfoMsgBodyCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been changed successfully. You may now log in..
        /// </summary>
        public static string InfoMsgPasswordResetSuccessBody {
            get {
                return ResourceManager.GetString("InfoMsgPasswordResetSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Reset.
        /// </summary>
        public static string InfoMsgPasswordResetSuccessTitle {
            get {
                return ResourceManager.GetString("InfoMsgPasswordResetSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A new verification code has been sent to your email..
        /// </summary>
        public static string InfoMsgResendSuccessBody {
            get {
                return ResourceManager.GetString("InfoMsgResendSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code Sent.
        /// </summary>
        public static string InfoMsgResendSuccessTitle {
            get {
                return ResourceManager.GetString("InfoMsgResendSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string InfoMsgTitleSuccess {
            get {
                return ResourceManager.GetString("InfoMsgTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been verified! You can now log in..
        /// </summary>
        public static string InfoMsgVerifySuccessBody {
            get {
                return ResourceManager.GetString("InfoMsgVerifySuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Verified.
        /// </summary>
        public static string InfoMsgVerifySuccessTitle {
            get {
                return ResourceManager.GetString("InfoMsgVerifySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score:.
        /// </summary>
        public static string InGameLbScore {
            get {
                return ResourceManager.GetString("InGameLbScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time:.
        /// </summary>
        public static string InGameLbTime {
            get {
                return ResourceManager.GetString("InGameLbTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You received an invitation from {0} to join lobby {1}..
        /// </summary>
        public static string InviteReceivedBody {
            get {
                return ResourceManager.GetString("InviteReceivedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby Invitation.
        /// </summary>
        public static string InviteReceivedTitle {
            get {
                return ResourceManager.GetString("InviteReceivedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation sent to {0}..
        /// </summary>
        public static string InviteSentBody {
            get {
                return ResourceManager.GetString("InviteSentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation Sent.
        /// </summary>
        public static string InviteSentTitle {
            get {
                return ResourceManager.GetString("InviteSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been kicked from the lobby. Reason: {0}.
        /// </summary>
        public static string KickedMessage {
            get {
                return ResourceManager.GetString("KickedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kicked.
        /// </summary>
        public static string KickedTitle {
            get {
                return ResourceManager.GetString("KickedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to kick {0}?.
        /// </summary>
        public static string KickPlayerMessage {
            get {
                return ResourceManager.GetString("KickPlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kick Player.
        /// </summary>
        public static string KickPlayerTitle {
            get {
                return ResourceManager.GetString("KickPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading friends list.
        /// </summary>
        public static string LoadFriendsError {
            get {
                return ResourceManager.GetString("LoadFriendsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friends.
        /// </summary>
        public static string LobbyBtnInvite {
            get {
                return ResourceManager.GetString("LobbyBtnInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Guest.
        /// </summary>
        public static string LobbyBtnInviteGuest {
            get {
                return ResourceManager.GetString("LobbyBtnInviteGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload Image....
        /// </summary>
        public static string LobbyBtnUploadImage {
            get {
                return ResourceManager.GetString("LobbyBtnUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string LobbyLbChat {
            get {
                return ResourceManager.GetString("LobbyLbChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIFFICULTY:.
        /// </summary>
        public static string LobbyLbDifficulty {
            get {
                return ResourceManager.GetString("LobbyLbDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAYERS:.
        /// </summary>
        public static string LobbyLbPlayers {
            get {
                return ResourceManager.GetString("LobbyLbPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string LobbyLbTitle {
            get {
                return ResourceManager.GetString("LobbyLbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting....
        /// </summary>
        public static string LobbyLbWaiting {
            get {
                return ResourceManager.GetString("LobbyLbWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search friends!.
        /// </summary>
        public static string LobbyTxtSearchFriends {
            get {
                return ResourceManager.GetString("LobbyTxtSearchFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account not verified.
        /// </summary>
        public static string LoginAccountNotVerified {
            get {
                return ResourceManager.GetString("LoginAccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as guest.
        /// </summary>
        public static string LoginBtnGuest {
            get {
                return ResourceManager.GetString("LoginBtnGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string LogInBtnLogin {
            get {
                return ResourceManager.GetString("LogInBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string LogInBtnRecover {
            get {
                return ResourceManager.GetString("LogInBtnRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LogInLbPassword {
            get {
                return ResourceManager.GetString("LogInLbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Lobby.
        /// </summary>
        public static string MainMenuBtnCreateLobby {
            get {
                return ResourceManager.GetString("MainMenuBtnCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXIT GAME.
        /// </summary>
        public static string MainMenuBtnExit {
            get {
                return ResourceManager.GetString("MainMenuBtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string MainMenuBtnJoin {
            get {
                return ResourceManager.GetString("MainMenuBtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOG OUT.
        /// </summary>
        public static string MainMenuBtnLogOut {
            get {
                return ResourceManager.GetString("MainMenuBtnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROFILE.
        /// </summary>
        public static string MainMenuBtnProfile {
            get {
                return ResourceManager.GetString("MainMenuBtnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Lobby by Code:.
        /// </summary>
        public static string MainMenuLbJoinCodePrompt {
            get {
                return ResourceManager.GetString("MainMenuLbJoinCodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need 4 players to start..
        /// </summary>
        public static string Need4PlayersError {
            get {
                return ResourceManager.GetString("Need4PlayersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didn&apos;t receive the code? Resend.
        /// </summary>
        public static string PasswordRecoveryBtnResend {
            get {
                return ResourceManager.GetString("PasswordRecoveryBtnResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string PasswordRecoveryBtnSave {
            get {
                return ResourceManager.GetString("PasswordRecoveryBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code to email.
        /// </summary>
        public static string PasswordRecoveryBtnSendCode {
            get {
                return ResourceManager.GetString("PasswordRecoveryBtnSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify code.
        /// </summary>
        public static string PasswordRecoveryBtnVerifyCode {
            get {
                return ResourceManager.GetString("PasswordRecoveryBtnVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password.
        /// </summary>
        public static string PasswordRecoveryLbConfirmPassword {
            get {
                return ResourceManager.GetString("PasswordRecoveryLbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a code to your email. Check your inbox (or spam folder) and enter it below..
        /// </summary>
        public static string PasswordRecoveryLbInstructions {
            get {
                return ResourceManager.GetString("PasswordRecoveryLbInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set new password.
        /// </summary>
        public static string PasswordRecoveryLbSetNew {
            get {
                return ResourceManager.GetString("PasswordRecoveryLbSetNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or email.
        /// </summary>
        public static string PasswordRecoveryLbUserEmail {
            get {
                return ResourceManager.GetString("PasswordRecoveryLbUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to Lobby.
        /// </summary>
        public static string PostMatchBtnBackToLobby {
            get {
                return ResourceManager.GetString("PostMatchBtnBackToLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        public static string PostMatchBtnMainMenu {
            get {
                return ResourceManager.GetString("PostMatchBtnMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pieces.
        /// </summary>
        public static string PostMatchHeaderPieces {
            get {
                return ResourceManager.GetString("PostMatchHeaderPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string PostMatchHeaderPlayer {
            get {
                return ResourceManager.GetString("PostMatchHeaderPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rank.
        /// </summary>
        public static string PostMatchHeaderRank {
            get {
                return ResourceManager.GetString("PostMatchHeaderRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pts.
        /// </summary>
        public static string PostMatchLbScoreSuffix {
            get {
                return ResourceManager.GetString("PostMatchLbScoreSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Results.
        /// </summary>
        public static string PostMatchLbTitle {
            get {
                return ResourceManager.GetString("PostMatchLbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WINNER.
        /// </summary>
        public static string PostMatchLbWinner {
            get {
                return ResourceManager.GetString("PostMatchLbWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Achievements.
        /// </summary>
        public static string ProfileLbAchievements {
            get {
                return ResourceManager.GetString("ProfileLbAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡HI, .
        /// </summary>
        public static string ProfileLbHi {
            get {
                return ResourceManager.GetString("ProfileLbHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highest Score:.
        /// </summary>
        public static string ProfileLbHighestScore {
            get {
                return ResourceManager.GetString("ProfileLbHighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal Information.
        /// </summary>
        public static string ProfileLbPersonalInfo {
            get {
                return ResourceManager.GetString("ProfileLbPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puzzles completed:.
        /// </summary>
        public static string ProfileLbPuzzlesCompleted {
            get {
                return ResourceManager.GetString("ProfileLbPuzzlesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puzzles won:.
        /// </summary>
        public static string ProfileLbPuzzlesWon {
            get {
                return ResourceManager.GetString("ProfileLbPuzzlesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats &amp; progression.
        /// </summary>
        public static string ProfileLbStats {
            get {
                return ResourceManager.GetString("ProfileLbStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total playtime:.
        /// </summary>
        public static string ProfileLbTotalPlaytime {
            get {
                return ResourceManager.GetString("ProfileLbTotalPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating profile..
        /// </summary>
        public static string ProfileUpdateError {
            get {
                return ResourceManager.GetString("ProfileUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile updated successfully!.
        /// </summary>
        public static string ProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("ProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language changed. The application needs to restart to apply changes. Restart now?.
        /// </summary>
        public static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart Required.
        /// </summary>
        public static string RestartRequiredTitle {
            get {
                return ResourceManager.GetString("RestartRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your Avatar!.
        /// </summary>
        public static string SelectAvatarTitle {
            get {
                return ResourceManager.GetString("SelectAvatarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Lobby.
        /// </summary>
        public static string SelectionPuzzleCreateLobbyBtn {
            get {
                return ResourceManager.GetString("SelectionPuzzleCreateLobbyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Puzzle &amp; Difficulty.
        /// </summary>
        public static string SelectionPuzzleHeader {
            get {
                return ResourceManager.GetString("SelectionPuzzleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Puzzle.
        /// </summary>
        public static string SelectionPuzzleTitle {
            get {
                return ResourceManager.GetString("SelectionPuzzleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload Your Image.
        /// </summary>
        public static string SelectionPuzzleUploadImageBtn {
            get {
                return ResourceManager.GetString("SelectionPuzzleUploadImageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Puzzle Image.
        /// </summary>
        public static string SelectPuzzleImageTitle {
            get {
                return ResourceManager.GetString("SelectPuzzleImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to send message: {0}.
        /// </summary>
        public static string SendChatError {
            get {
                return ResourceManager.GetString("SendChatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sending lobby invite.
        /// </summary>
        public static string SendInviteError {
            get {
                return ResourceManager.GetString("SendInviteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREDITS.
        /// </summary>
        public static string SettingsBtnCredits {
            get {
                return ResourceManager.GetString("SettingsBtnCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RELOAD PROGRESS.
        /// </summary>
        public static string SettingsBtnReloadProgress {
            get {
                return ResourceManager.GetString("SettingsBtnReloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE AND EXIT.
        /// </summary>
        public static string SettingsBtnSaveExit {
            get {
                return ResourceManager.GetString("SettingsBtnSaveExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERAL.
        /// </summary>
        public static string SettingsLbGeneral {
            get {
                return ResourceManager.GetString("SettingsLbGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LANGUAGE.
        /// </summary>
        public static string SettingsLbLanguage {
            get {
                return ResourceManager.GetString("SettingsLbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MUSIC.
        /// </summary>
        public static string SettingsLbMusic {
            get {
                return ResourceManager.GetString("SettingsLbMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOUND.
        /// </summary>
        public static string SettingsLbSound {
            get {
                return ResourceManager.GetString("SettingsLbSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOUND EFFECTS.
        /// </summary>
        public static string SettingsLbSoundEffects {
            get {
                return ResourceManager.GetString("SettingsLbSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VIBRATION.
        /// </summary>
        public static string SettingsLbVibration {
            get {
                return ResourceManager.GetString("SettingsLbVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENGLISH.
        /// </summary>
        public static string SettingsOptEnglish {
            get {
                return ResourceManager.GetString("SettingsOptEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPANISH.
        /// </summary>
        public static string SettingsOptSpanish {
            get {
                return ResourceManager.GetString("SettingsOptSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an account? Log in.
        /// </summary>
        public static string SignUpLbAlreadyAccount {
            get {
                return ResourceManager.GetString("SignUpLbAlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create your account.
        /// </summary>
        public static string SignUpLbNewAccount {
            get {
                return ResourceManager.GetString("SignUpLbNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string SignUpRbFemale {
            get {
                return ResourceManager.GetString("SignUpRbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string SignUpRbMale {
            get {
                return ResourceManager.GetString("SignUpRbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prefer not to say.
        /// </summary>
        public static string SignUpRbNoSay {
            get {
                return ResourceManager.GetString("SignUpRbNoSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string SignUpRbOther {
            get {
                return ResourceManager.GetString("SignUpRbOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string SocialBtnAccept {
            get {
                return ResourceManager.GetString("SocialBtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string SocialBtnDecline {
            get {
                return ResourceManager.GetString("SocialBtnDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends list.
        /// </summary>
        public static string SocialBtnFriendsList {
            get {
                return ResourceManager.GetString("SocialBtnFriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests.
        /// </summary>
        public static string SocialBtnRequests {
            get {
                return ResourceManager.GetString("SocialBtnRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove {0}?.
        /// </summary>
        public static string SocialConfirmRemove {
            get {
                return ResourceManager.GetString("SocialConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Removal.
        /// </summary>
        public static string SocialConfirmRemoveTitle {
            get {
                return ResourceManager.GetString("SocialConfirmRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Friend!.
        /// </summary>
        public static string SocialInfoNewFriendTitle {
            get {
                return ResourceManager.GetString("SocialInfoNewFriendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have received a new friend request from {0}..
        /// </summary>
        public static string SocialInfoNewRequest {
            get {
                return ResourceManager.GetString("SocialInfoNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Friend Request.
        /// </summary>
        public static string SocialInfoNewRequestTitle {
            get {
                return ResourceManager.GetString("SocialInfoNewRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has accepted your friend request..
        /// </summary>
        public static string SocialInfoRequestAccepted {
            get {
                return ResourceManager.GetString("SocialInfoRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has declined your friend request..
        /// </summary>
        public static string SocialInfoRequestDeclined {
            get {
                return ResourceManager.GetString("SocialInfoRequestDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request Declined.
        /// </summary>
        public static string SocialInfoRequestDeclinedTitle {
            get {
                return ResourceManager.GetString("SocialInfoRequestDeclinedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string SocialLbOffline {
            get {
                return ResourceManager.GetString("SocialLbOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string SocialLbOnline {
            get {
                return ResourceManager.GetString("SocialLbOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received requests:.
        /// </summary>
        public static string SocialLbReceivedRequests {
            get {
                return ResourceManager.GetString("SocialLbReceivedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string SocialLbSearch {
            get {
                return ResourceManager.GetString("SocialLbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search result:.
        /// </summary>
        public static string SocialLbSearchResult {
            get {
                return ResourceManager.GetString("SocialLbSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent requests:.
        /// </summary>
        public static string SocialLbSentRequests {
            get {
                return ResourceManager.GetString("SocialLbSentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove friend.
        /// </summary>
        public static string SocialToolTipRemoveFriend {
            get {
                return ResourceManager.GetString("SocialToolTipRemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully joined the lobby as a guest..
        /// </summary>
        public static string SuccessGuestJoinedLobby {
            get {
                return ResourceManager.GetString("SuccessGuestJoinedLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby closed because the host was expelled..
        /// </summary>
        public static string SystemHostExpelled {
            get {
                return ResourceManager.GetString("SystemHostExpelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [SYSTEM] Message blocked. Strike {0}/3. Watch your language..
        /// </summary>
        public static string SystemMessageBlocked {
            get {
                return ResourceManager.GetString("SystemMessageBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload Failed.
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload successful!.
        /// </summary>
        public static string UploadSuccessful {
            get {
                return ResourceManager.GetString("UploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must be at least 13 years old and the date cannot be in the future..
        /// </summary>
        public static string ValidationBirthDateInvalid {
            get {
                return ResourceManager.GetString("ValidationBirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth is required..
        /// </summary>
        public static string ValidationBirthDateRequired {
            get {
                return ResourceManager.GetString("ValidationBirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password is required..
        /// </summary>
        public static string ValidationCurrentPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationCurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email format is invalid..
        /// </summary>
        public static string ValidationEmailInvalid {
            get {
                return ResourceManager.GetString("ValidationEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is required..
        /// </summary>
        public static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name is required..
        /// </summary>
        public static string ValidationFirstNameRequired {
            get {
                return ResourceManager.GetString("ValidationFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a gender option..
        /// </summary>
        public static string ValidationGenderRequired {
            get {
                return ResourceManager.GetString("ValidationGenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name is required..
        /// </summary>
        public static string ValidationLastNameRequired {
            get {
                return ResourceManager.GetString("ValidationLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code must be 6 alphanumeric characters..
        /// </summary>
        public static string ValidationLobbyCodeFormat {
            get {
                return ResourceManager.GetString("ValidationLobbyCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby code is required..
        /// </summary>
        public static string ValidationLobbyCodeRequired {
            get {
                return ResourceManager.GetString("ValidationLobbyCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please confirm your password..
        /// </summary>
        public static string ValidationPasswordConfirmRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password is required..
        /// </summary>
        public static string ValidationPasswordNewRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordNewRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be 8+ chars, 1 uppercase, 1 lowercase, 1 number, and 1 symbol..
        /// </summary>
        public static string ValidationPasswordPolicy {
            get {
                return ResourceManager.GetString("ValidationPasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A recovery code has been sent to your email..
        /// </summary>
        public static string ValidationPasswordRecoveryCodeSent {
            get {
                return ResourceManager.GetString("ValidationPasswordRecoveryCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required..
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords do not match..
        /// </summary>
        public static string ValidationPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username must be between 3 and 16 characters..
        /// </summary>
        public static string ValidationUsernameLength {
            get {
                return ResourceManager.GetString("ValidationUsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username is required..
        /// </summary>
        public static string ValidationUsernameRequired {
            get {
                return ResourceManager.GetString("ValidationUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code must be 6 numeric digits..
        /// </summary>
        public static string ValidationVerificationCodeFormat {
            get {
                return ResourceManager.GetString("ValidationVerificationCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code is required..
        /// </summary>
        public static string ValidationVerificationCodeRequired {
            get {
                return ResourceManager.GetString("ValidationVerificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Account.
        /// </summary>
        public static string VerificationAccountBtnVerify {
            get {
                return ResourceManager.GetString("VerificationAccountBtnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a 6-digit code to your email. Please enter it below to activate your account..
        /// </summary>
        public static string VerificationAccountLbInstructions {
            get {
                return ResourceManager.GetString("VerificationAccountLbInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Your Account.
        /// </summary>
        public static string VerificationAccountLbTitle {
            get {
                return ResourceManager.GetString("VerificationAccountLbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code must contain 6 digits only..
        /// </summary>
        public static string VerificationCodeInvalidFormat {
            get {
                return ResourceManager.GetString("VerificationCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didn&apos;t receive the code? Resend.
        /// </summary>
        public static string VerificationCodeResend {
            get {
                return ResourceManager.GetString("VerificationCodeResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to matchmaking service..
        /// </summary>
        public static string WarningMsgMatchmakingConnectFailed {
            get {
                return ResourceManager.GetString("WarningMsgMatchmakingConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to social features. Friend lists and invites might not work..
        /// </summary>
        public static string WarningMsgSocialConnectFailed {
            get {
                return ResourceManager.GetString("WarningMsgSocialConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to social features. Chat might not work correctly..
        /// </summary>
        public static string WarningMsgSocialConnectFailedGuest {
            get {
                return ResourceManager.GetString("WarningMsgSocialConnectFailedGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
