//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveClient.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindWeaveClient.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Avatar.
        /// </summary>
        public static string EditProfileBtnChangeAvatar {
            get {
                return ResourceManager.GetString("EditProfileBtnChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string EditProfileBtnChangePassword {
            get {
                return ResourceManager.GetString("EditProfileBtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save changes.
        /// </summary>
        public static string EditProfileBtnSaveChanges {
            get {
                return ResourceManager.GetString("EditProfileBtnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar los datos del perfil.
        /// </summary>
        public static string ErrorFailedToLoadProfile {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string GlobalBtnAddFriend {
            get {
                return ResourceManager.GetString("GlobalBtnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string GlobalBtnBack {
            get {
                return ResourceManager.GetString("GlobalBtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string GlobalBtnCancel {
            get {
                return ResourceManager.GetString("GlobalBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAY.
        /// </summary>
        public static string GlobalBtnPlay {
            get {
                return ResourceManager.GetString("GlobalBtnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string GlobalBtnSignUp {
            get {
                return ResourceManager.GetString("GlobalBtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit profile.
        /// </summary>
        public static string GlobalCommonEditProfile {
            get {
                return ResourceManager.GetString("GlobalCommonEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SETTINGS.
        /// </summary>
        public static string GlobalCommonSettings {
            get {
                return ResourceManager.GetString("GlobalCommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOCIAL.
        /// </summary>
        public static string GlobalCommonSocial {
            get {
                return ResourceManager.GetString("GlobalCommonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth.
        /// </summary>
        public static string GlobalLbBirth {
            get {
                return ResourceManager.GetString("GlobalLbBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string GlobalLbEmail {
            get {
                return ResourceManager.GetString("GlobalLbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        public static string GlobalLbFirstName {
            get {
                return ResourceManager.GetString("GlobalLbFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mind Weave.
        /// </summary>
        public static string GlobalLbGameName {
            get {
                return ResourceManager.GetString("GlobalLbGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género.
        /// </summary>
        public static string GlobalLbGender {
            get {
                return ResourceManager.GetString("GlobalLbGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string GlobalLbLastName {
            get {
                return ResourceManager.GetString("GlobalLbLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password recovery.
        /// </summary>
        public static string GlobalLbPasswordRecovery {
            get {
                return ResourceManager.GetString("GlobalLbPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string GlobalLbUsername {
            get {
                return ResourceManager.GetString("GlobalLbUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string GlobalTxtNewPassword {
            get {
                return ResourceManager.GetString("GlobalTxtNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code sent successfully.
        /// </summary>
        public static string InfoMsgBodyCodeSent {
            get {
                return ResourceManager.GetString("InfoMsgBodyCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string InfoMsgTitleSuccess {
            get {
                return ResourceManager.GetString("InfoMsgTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score:.
        /// </summary>
        public static string InGameLbScore {
            get {
                return ResourceManager.GetString("InGameLbScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time:.
        /// </summary>
        public static string InGameLbTime {
            get {
                return ResourceManager.GetString("InGameLbTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friends.
        /// </summary>
        public static string LobbyBtnInvite {
            get {
                return ResourceManager.GetString("LobbyBtnInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload Image....
        /// </summary>
        public static string LobbyBtnUploadImage {
            get {
                return ResourceManager.GetString("LobbyBtnUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string LobbyLbChat {
            get {
                return ResourceManager.GetString("LobbyLbChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIFFICULTY:.
        /// </summary>
        public static string LobbyLbDifficulty {
            get {
                return ResourceManager.GetString("LobbyLbDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAYERS:.
        /// </summary>
        public static string LobbyLbPlayers {
            get {
                return ResourceManager.GetString("LobbyLbPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string LobbyLbTitle {
            get {
                return ResourceManager.GetString("LobbyLbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting....
        /// </summary>
        public static string LobbyLbWaiting {
            get {
                return ResourceManager.GetString("LobbyLbWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search friends!.
        /// </summary>
        public static string LobbyTxtSearchFriends {
            get {
                return ResourceManager.GetString("LobbyTxtSearchFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as guest.
        /// </summary>
        public static string LoginBtnGuest {
            get {
                return ResourceManager.GetString("LoginBtnGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string LogInBtnLogin {
            get {
                return ResourceManager.GetString("LogInBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string LogInBtnRecover {
            get {
                return ResourceManager.GetString("LogInBtnRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LogInLbPassword {
            get {
                return ResourceManager.GetString("LogInLbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROFILE.
        /// </summary>
        public static string MainMenuBtnProfile {
            get {
                return ResourceManager.GetString("MainMenuBtnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didn&apos;t receive the code? Resend.
        /// </summary>
        public static string PasswordRecoveryBtnResend {
            get {
                return ResourceManager.GetString("PasswordRecoveryBtnResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string PasswordRecoveryBtnSave {
            get {
                return ResourceManager.GetString("PasswordRecoveryBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code to email.
        /// </summary>
        public static string PasswordRecoveryBtnSendCode {
            get {
                return ResourceManager.GetString("PasswordRecoveryBtnSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify code.
        /// </summary>
        public static string PasswordRecoveryBtnVerifyCode {
            get {
                return ResourceManager.GetString("PasswordRecoveryBtnVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password.
        /// </summary>
        public static string PasswordRecoveryLbConfirmPassword {
            get {
                return ResourceManager.GetString("PasswordRecoveryLbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a code to your email. Check your inbox (or spam folder) and enter it below..
        /// </summary>
        public static string PasswordRecoveryLbInstructions {
            get {
                return ResourceManager.GetString("PasswordRecoveryLbInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set new password.
        /// </summary>
        public static string PasswordRecoveryLbSetNew {
            get {
                return ResourceManager.GetString("PasswordRecoveryLbSetNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or email.
        /// </summary>
        public static string PasswordRecoveryLbUserEmail {
            get {
                return ResourceManager.GetString("PasswordRecoveryLbUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Achievements.
        /// </summary>
        public static string ProfileLbAchievements {
            get {
                return ResourceManager.GetString("ProfileLbAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡HI, .
        /// </summary>
        public static string ProfileLbHi {
            get {
                return ResourceManager.GetString("ProfileLbHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highest Score:.
        /// </summary>
        public static string ProfileLbHighestScore {
            get {
                return ResourceManager.GetString("ProfileLbHighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal Information.
        /// </summary>
        public static string ProfileLbPersonalInfo {
            get {
                return ResourceManager.GetString("ProfileLbPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puzzles completed:.
        /// </summary>
        public static string ProfileLbPuzzlesCompleted {
            get {
                return ResourceManager.GetString("ProfileLbPuzzlesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puzzles won:.
        /// </summary>
        public static string ProfileLbPuzzlesWon {
            get {
                return ResourceManager.GetString("ProfileLbPuzzlesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats &amp; progression.
        /// </summary>
        public static string ProfileLbStats {
            get {
                return ResourceManager.GetString("ProfileLbStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total playtime:.
        /// </summary>
        public static string ProfileLbTotalPlaytime {
            get {
                return ResourceManager.GetString("ProfileLbTotalPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your Avatar!.
        /// </summary>
        public static string SelectAvatarTitle {
            get {
                return ResourceManager.GetString("SelectAvatarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREDITS.
        /// </summary>
        public static string SettingsBtnCredits {
            get {
                return ResourceManager.GetString("SettingsBtnCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RELOAD PROGRESS.
        /// </summary>
        public static string SettingsBtnReloadProgress {
            get {
                return ResourceManager.GetString("SettingsBtnReloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE AND EXIT.
        /// </summary>
        public static string SettingsBtnSaveExit {
            get {
                return ResourceManager.GetString("SettingsBtnSaveExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERAL.
        /// </summary>
        public static string SettingsLbGeneral {
            get {
                return ResourceManager.GetString("SettingsLbGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LANGUAGE.
        /// </summary>
        public static string SettingsLbLanguage {
            get {
                return ResourceManager.GetString("SettingsLbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MUSIC.
        /// </summary>
        public static string SettingsLbMusic {
            get {
                return ResourceManager.GetString("SettingsLbMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOUND.
        /// </summary>
        public static string SettingsLbSound {
            get {
                return ResourceManager.GetString("SettingsLbSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOUND EFFECTS.
        /// </summary>
        public static string SettingsLbSoundEffects {
            get {
                return ResourceManager.GetString("SettingsLbSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VIBRATION.
        /// </summary>
        public static string SettingsLbVibration {
            get {
                return ResourceManager.GetString("SettingsLbVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENGLISH.
        /// </summary>
        public static string SettingsOptEnglish {
            get {
                return ResourceManager.GetString("SettingsOptEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPANISH.
        /// </summary>
        public static string SettingsOptSpanish {
            get {
                return ResourceManager.GetString("SettingsOptSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an account? Log in.
        /// </summary>
        public static string SignUpLbAlreadyAccount {
            get {
                return ResourceManager.GetString("SignUpLbAlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create your account.
        /// </summary>
        public static string SignUpLbNewAccount {
            get {
                return ResourceManager.GetString("SignUpLbNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string SignUpRbFemale {
            get {
                return ResourceManager.GetString("SignUpRbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string SignUpRbMale {
            get {
                return ResourceManager.GetString("SignUpRbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prefer not to say.
        /// </summary>
        public static string SignUpRbNoSay {
            get {
                return ResourceManager.GetString("SignUpRbNoSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string SignUpRbOther {
            get {
                return ResourceManager.GetString("SignUpRbOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string SocialBtnAccept {
            get {
                return ResourceManager.GetString("SocialBtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string SocialBtnDecline {
            get {
                return ResourceManager.GetString("SocialBtnDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends list.
        /// </summary>
        public static string SocialBtnFriendsList {
            get {
                return ResourceManager.GetString("SocialBtnFriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests.
        /// </summary>
        public static string SocialBtnRequests {
            get {
                return ResourceManager.GetString("SocialBtnRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string SocialLbOffline {
            get {
                return ResourceManager.GetString("SocialLbOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string SocialLbOnline {
            get {
                return ResourceManager.GetString("SocialLbOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received requests:.
        /// </summary>
        public static string SocialLbReceivedRequests {
            get {
                return ResourceManager.GetString("SocialLbReceivedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string SocialLbSearch {
            get {
                return ResourceManager.GetString("SocialLbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search result:.
        /// </summary>
        public static string SocialLbSearchResult {
            get {
                return ResourceManager.GetString("SocialLbSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent requests:.
        /// </summary>
        public static string SocialLbSentRequests {
            get {
                return ResourceManager.GetString("SocialLbSentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Account.
        /// </summary>
        public static string VerificationAccountBtnVerify {
            get {
                return ResourceManager.GetString("VerificationAccountBtnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a 6-digit code to your email. Please enter it below to activate your account..
        /// </summary>
        public static string VerificationAccountLbInstructions {
            get {
                return ResourceManager.GetString("VerificationAccountLbInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Your Account.
        /// </summary>
        public static string VerificationAccountLbTitle {
            get {
                return ResourceManager.GetString("VerificationAccountLbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación solo debe contener 6 números..
        /// </summary>
        public static string VerificationCodeInvalidFormat {
            get {
                return ResourceManager.GetString("VerificationCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No recibiste el código? Reenviar.
        /// </summary>
        public static string VerificationCodeResend {
            get {
                return ResourceManager.GetString("VerificationCodeResend", resourceCulture);
            }
        }
    }
}
