//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveClient.MatchmakingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbySettingsDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class LobbySettingsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CustomPuzzleImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DifficultyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PreloadedPuzzleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] CustomPuzzleImage {
            get {
                return this.CustomPuzzleImageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomPuzzleImageField, value) != true)) {
                    this.CustomPuzzleImageField = value;
                    this.RaisePropertyChanged("CustomPuzzleImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DifficultyId {
            get {
                return this.DifficultyIdField;
            }
            set {
                if ((this.DifficultyIdField.Equals(value) != true)) {
                    this.DifficultyIdField = value;
                    this.RaisePropertyChanged("DifficultyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PreloadedPuzzleId {
            get {
                return this.PreloadedPuzzleIdField;
            }
            set {
                if ((this.PreloadedPuzzleIdField.Equals(value) != true)) {
                    this.PreloadedPuzzleIdField = value;
                    this.RaisePropertyChanged("PreloadedPuzzleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
        "hared")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MindWeaveClient.MatchmakingService.GuestJoinResultDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MindWeaveClient.MatchmakingService.LobbyCreationResultDto))]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestJoinResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class GuestJoinResultDto : MindWeaveClient.MatchmakingService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedGuestUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.LobbyStateDto InitialLobbyStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedGuestUsername {
            get {
                return this.AssignedGuestUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedGuestUsernameField, value) != true)) {
                    this.AssignedGuestUsernameField = value;
                    this.RaisePropertyChanged("AssignedGuestUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.LobbyStateDto InitialLobbyState {
            get {
                return this.InitialLobbyStateField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialLobbyStateField, value) != true)) {
                    this.InitialLobbyStateField = value;
                    this.RaisePropertyChanged("InitialLobbyState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyCreationResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class LobbyCreationResultDto : MindWeaveClient.MatchmakingService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.LobbyStateDto InitialLobbyStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.LobbyStateDto InitialLobbyState {
            get {
                return this.InitialLobbyStateField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialLobbyStateField, value) != true)) {
                    this.InitialLobbyStateField = value;
                    this.RaisePropertyChanged("InitialLobbyState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyStateDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class LobbyStateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.LobbySettingsDto CurrentSettingsDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuzzleImagePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.LobbySettingsDto CurrentSettingsDto {
            get {
                return this.CurrentSettingsDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentSettingsDtoField, value) != true)) {
                    this.CurrentSettingsDtoField = value;
                    this.RaisePropertyChanged("CurrentSettingsDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostUsername {
            get {
                return this.HostUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostUsernameField, value) != true)) {
                    this.HostUsernameField = value;
                    this.RaisePropertyChanged("HostUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyId {
            get {
                return this.LobbyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyIdField, value) != true)) {
                    this.LobbyIdField = value;
                    this.RaisePropertyChanged("LobbyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuzzleImagePath {
            get {
                return this.PuzzleImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.PuzzleImagePathField, value) != true)) {
                    this.PuzzleImagePathField = value;
                    this.RaisePropertyChanged("PuzzleImagePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
        "hared")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.ServiceErrorType ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.ServiceErrorType ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((this.ErrorTypeField.Equals(value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorType", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
        "hared")]
    public enum ServiceErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRecord = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationFailed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameInProgress = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationError = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecurityError = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestInvitationDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class GuestInvitationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuestEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InviterUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuestEmail {
            get {
                return this.GuestEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestEmailField, value) != true)) {
                    this.GuestEmailField = value;
                    this.RaisePropertyChanged("GuestEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InviterUsername {
            get {
                return this.InviterUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.InviterUsernameField, value) != true)) {
                    this.InviterUsernameField = value;
                    this.RaisePropertyChanged("InviterUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestJoinRequestDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class GuestJoinRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesiredGuestUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuestEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesiredGuestUsername {
            get {
                return this.DesiredGuestUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.DesiredGuestUsernameField, value) != true)) {
                    this.DesiredGuestUsernameField = value;
                    this.RaisePropertyChanged("DesiredGuestUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuestEmail {
            get {
                return this.GuestEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestEmailField, value) != true)) {
                    this.GuestEmailField = value;
                    this.RaisePropertyChanged("GuestEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuzzleDefinitionDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.P" +
        "uzzle")]
    [System.SerializableAttribute()]
    public partial class PuzzleDefinitionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FullImageBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.PuzzlePieceDefinitionDto[] PiecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuzzleHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuzzleWidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FullImageBytes {
            get {
                return this.FullImageBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.FullImageBytesField, value) != true)) {
                    this.FullImageBytesField = value;
                    this.RaisePropertyChanged("FullImageBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.PuzzlePieceDefinitionDto[] Pieces {
            get {
                return this.PiecesField;
            }
            set {
                if ((object.ReferenceEquals(this.PiecesField, value) != true)) {
                    this.PiecesField = value;
                    this.RaisePropertyChanged("Pieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuzzleHeight {
            get {
                return this.PuzzleHeightField;
            }
            set {
                if ((this.PuzzleHeightField.Equals(value) != true)) {
                    this.PuzzleHeightField = value;
                    this.RaisePropertyChanged("PuzzleHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuzzleWidth {
            get {
                return this.PuzzleWidthField;
            }
            set {
                if ((this.PuzzleWidthField.Equals(value) != true)) {
                    this.PuzzleWidthField = value;
                    this.RaisePropertyChanged("PuzzleWidth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuzzlePieceDefinitionDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.P" +
        "uzzle")]
    [System.SerializableAttribute()]
    public partial class PuzzlePieceDefinitionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BottomNeighborIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CorrectXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CorrectYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitialXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitialYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LeftNeighborIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PieceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RightNeighborIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TopNeighborIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BottomNeighborId {
            get {
                return this.BottomNeighborIdField;
            }
            set {
                if ((this.BottomNeighborIdField.Equals(value) != true)) {
                    this.BottomNeighborIdField = value;
                    this.RaisePropertyChanged("BottomNeighborId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CorrectX {
            get {
                return this.CorrectXField;
            }
            set {
                if ((this.CorrectXField.Equals(value) != true)) {
                    this.CorrectXField = value;
                    this.RaisePropertyChanged("CorrectX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CorrectY {
            get {
                return this.CorrectYField;
            }
            set {
                if ((this.CorrectYField.Equals(value) != true)) {
                    this.CorrectYField = value;
                    this.RaisePropertyChanged("CorrectY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialX {
            get {
                return this.InitialXField;
            }
            set {
                if ((this.InitialXField.Equals(value) != true)) {
                    this.InitialXField = value;
                    this.RaisePropertyChanged("InitialX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialY {
            get {
                return this.InitialYField;
            }
            set {
                if ((this.InitialYField.Equals(value) != true)) {
                    this.InitialYField = value;
                    this.RaisePropertyChanged("InitialY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LeftNeighborId {
            get {
                return this.LeftNeighborIdField;
            }
            set {
                if ((this.LeftNeighborIdField.Equals(value) != true)) {
                    this.LeftNeighborIdField = value;
                    this.RaisePropertyChanged("LeftNeighborId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PieceId {
            get {
                return this.PieceIdField;
            }
            set {
                if ((this.PieceIdField.Equals(value) != true)) {
                    this.PieceIdField = value;
                    this.RaisePropertyChanged("PieceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RightNeighborId {
            get {
                return this.RightNeighborIdField;
            }
            set {
                if ((this.RightNeighborIdField.Equals(value) != true)) {
                    this.RightNeighborIdField = value;
                    this.RaisePropertyChanged("RightNeighborId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceX {
            get {
                return this.SourceXField;
            }
            set {
                if ((this.SourceXField.Equals(value) != true)) {
                    this.SourceXField = value;
                    this.RaisePropertyChanged("SourceX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceY {
            get {
                return this.SourceYField;
            }
            set {
                if ((this.SourceYField.Equals(value) != true)) {
                    this.SourceYField = value;
                    this.RaisePropertyChanged("SourceY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TopNeighborId {
            get {
                return this.TopNeighborIdField;
            }
            set {
                if ((this.TopNeighborIdField.Equals(value) != true)) {
                    this.TopNeighborIdField = value;
                    this.RaisePropertyChanged("TopNeighborId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchEndResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.G" +
        "ame")]
    [System.SerializableAttribute()]
    public partial class MatchEndResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.PlayerResultDto[] PlayerResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalTimeElapsedSecondsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.PlayerResultDto[] PlayerResults {
            get {
                return this.PlayerResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerResultsField, value) != true)) {
                    this.PlayerResultsField = value;
                    this.RaisePropertyChanged("PlayerResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalTimeElapsedSeconds {
            get {
                return this.TotalTimeElapsedSecondsField;
            }
            set {
                if ((this.TotalTimeElapsedSecondsField.Equals(value) != true)) {
                    this.TotalTimeElapsedSecondsField = value;
                    this.RaisePropertyChanged("TotalTimeElapsedSeconds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.G" +
        "ame")]
    [System.SerializableAttribute()]
    public partial class PlayerResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PiecesPlacedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] UnlockedAchievementIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWinner {
            get {
                return this.IsWinnerField;
            }
            set {
                if ((this.IsWinnerField.Equals(value) != true)) {
                    this.IsWinnerField = value;
                    this.RaisePropertyChanged("IsWinner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PiecesPlaced {
            get {
                return this.PiecesPlacedField;
            }
            set {
                if ((this.PiecesPlacedField.Equals(value) != true)) {
                    this.PiecesPlacedField = value;
                    this.RaisePropertyChanged("PiecesPlaced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] UnlockedAchievementIds {
            get {
                return this.UnlockedAchievementIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.UnlockedAchievementIdsField, value) != true)) {
                    this.UnlockedAchievementIdsField = value;
                    this.RaisePropertyChanged("UnlockedAchievementIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchmakingService.IMatchmakingManager", CallbackContract=typeof(MindWeaveClient.MatchmakingService.IMatchmakingManagerCallback))]
    public interface IMatchmakingManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/createLobby", ReplyAction="http://tempuri.org/IMatchmakingManager/createLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MindWeaveClient.MatchmakingService.ServiceFaultDto), Action="http://tempuri.org/IMatchmakingManager/createLobbyServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
            "hared")]
        MindWeaveClient.MatchmakingService.LobbyCreationResultDto createLobby(string hostUsername, MindWeaveClient.MatchmakingService.LobbySettingsDto settingsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/createLobby", ReplyAction="http://tempuri.org/IMatchmakingManager/createLobbyResponse")]
        System.Threading.Tasks.Task<MindWeaveClient.MatchmakingService.LobbyCreationResultDto> createLobbyAsync(string hostUsername, MindWeaveClient.MatchmakingService.LobbySettingsDto settingsDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/inviteToLobby")]
        void inviteToLobby(string inviterUsername, string invitedUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/inviteToLobby")]
        System.Threading.Tasks.Task inviteToLobbyAsync(string inviterUsername, string invitedUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/joinLobby")]
        void joinLobby(string username, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/joinLobby")]
        System.Threading.Tasks.Task joinLobbyAsync(string username, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/leaveLobby")]
        void leaveLobby(string username, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/leaveLobby")]
        System.Threading.Tasks.Task leaveLobbyAsync(string username, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/startGame")]
        void startGame(string hostUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/startGame")]
        System.Threading.Tasks.Task startGameAsync(string hostUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/kickPlayer")]
        void kickPlayer(string hostUsername, string playerToKickUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/kickPlayer")]
        System.Threading.Tasks.Task kickPlayerAsync(string hostUsername, string playerToKickUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/changeDifficulty")]
        void changeDifficulty(string hostUsername, string lobbyId, int newDifficultyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/changeDifficulty")]
        System.Threading.Tasks.Task changeDifficultyAsync(string hostUsername, string lobbyId, int newDifficultyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/inviteGuestByEmail")]
        void inviteGuestByEmail(MindWeaveClient.MatchmakingService.GuestInvitationDto invitationData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/inviteGuestByEmail")]
        System.Threading.Tasks.Task inviteGuestByEmailAsync(MindWeaveClient.MatchmakingService.GuestInvitationDto invitationData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuest", ReplyAction="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MindWeaveClient.MatchmakingService.ServiceFaultDto), Action="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuestServiceFaultDtoFault", Name="ServiceFaultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
            "hared")]
        MindWeaveClient.MatchmakingService.GuestJoinResultDto joinLobbyAsGuest(MindWeaveClient.MatchmakingService.GuestJoinRequestDto joinRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuest", ReplyAction="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuestResponse")]
        System.Threading.Tasks.Task<MindWeaveClient.MatchmakingService.GuestJoinResultDto> joinLobbyAsGuestAsync(MindWeaveClient.MatchmakingService.GuestJoinRequestDto joinRequest);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/requestPieceDrag")]
        void requestPieceDrag(string lobbyCode, int pieceId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/requestPieceDrag")]
        System.Threading.Tasks.Task requestPieceDragAsync(string lobbyCode, int pieceId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/requestPieceMove")]
        void requestPieceMove(string lobbyCode, int pieceId, double newX, double newY);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/requestPieceMove")]
        System.Threading.Tasks.Task requestPieceMoveAsync(string lobbyCode, int pieceId, double newX, double newY);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/requestPieceDrop")]
        void requestPieceDrop(string lobbyCode, int pieceId, double newX, double newY);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/requestPieceDrop")]
        System.Threading.Tasks.Task requestPieceDropAsync(string lobbyCode, int pieceId, double newX, double newY);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/requestPieceRelease")]
        void requestPieceRelease(string lobbyCode, int pieceId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/requestPieceRelease")]
        System.Threading.Tasks.Task requestPieceReleaseAsync(string lobbyCode, int pieceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/updateLobbyState")]
        void updateLobbyState(MindWeaveClient.MatchmakingService.LobbyStateDto lobbyStateDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/matchFound")]
        void matchFound(string lobbyCode, string[] players, MindWeaveClient.MatchmakingService.LobbySettingsDto settings, string puzzleImagePath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/lobbyCreationFailed")]
        void lobbyCreationFailed(string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/notifyLobbyActionFailed")]
        void notifyLobbyActionFailed(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/kickedFromLobby")]
        void kickedFromLobby(string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/onGameStarted")]
        void onGameStarted(MindWeaveClient.MatchmakingService.PuzzleDefinitionDto puzzleDefinition, int matchDurationSeconds);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/onPieceDragStarted")]
        void onPieceDragStarted(int pieceId, string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/onPiecePlaced")]
        void onPiecePlaced(int pieceId, double correctX, double correctY, string username, int newScore, string bonusType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/onPieceMoved")]
        void onPieceMoved(int pieceId, double newX, double newY, string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/onPieceDragReleased")]
        void onPieceDragReleased(int pieceId, string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/onGameEnded")]
        void onGameEnded(MindWeaveClient.MatchmakingService.MatchEndResultDto result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/onPlayerPenalty")]
        void onPlayerPenalty(string username, int pointsLost, int newScore, string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/lobbyDestroyed")]
        void lobbyDestroyed(string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/OnAchievementUnlocked")]
        void OnAchievementUnlocked(string achievementKey, string imageName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerChannel : MindWeaveClient.MatchmakingService.IMatchmakingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchmakingManagerClient : System.ServiceModel.DuplexClientBase<MindWeaveClient.MatchmakingService.IMatchmakingManager>, MindWeaveClient.MatchmakingService.IMatchmakingManager {
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public MindWeaveClient.MatchmakingService.LobbyCreationResultDto createLobby(string hostUsername, MindWeaveClient.MatchmakingService.LobbySettingsDto settingsDto) {
            return base.Channel.createLobby(hostUsername, settingsDto);
        }
        
        public System.Threading.Tasks.Task<MindWeaveClient.MatchmakingService.LobbyCreationResultDto> createLobbyAsync(string hostUsername, MindWeaveClient.MatchmakingService.LobbySettingsDto settingsDto) {
            return base.Channel.createLobbyAsync(hostUsername, settingsDto);
        }
        
        public void inviteToLobby(string inviterUsername, string invitedUsername, string lobbyId) {
            base.Channel.inviteToLobby(inviterUsername, invitedUsername, lobbyId);
        }
        
        public System.Threading.Tasks.Task inviteToLobbyAsync(string inviterUsername, string invitedUsername, string lobbyId) {
            return base.Channel.inviteToLobbyAsync(inviterUsername, invitedUsername, lobbyId);
        }
        
        public void joinLobby(string username, string lobbyId) {
            base.Channel.joinLobby(username, lobbyId);
        }
        
        public System.Threading.Tasks.Task joinLobbyAsync(string username, string lobbyId) {
            return base.Channel.joinLobbyAsync(username, lobbyId);
        }
        
        public void leaveLobby(string username, string lobbyId) {
            base.Channel.leaveLobby(username, lobbyId);
        }
        
        public System.Threading.Tasks.Task leaveLobbyAsync(string username, string lobbyId) {
            return base.Channel.leaveLobbyAsync(username, lobbyId);
        }
        
        public void startGame(string hostUsername, string lobbyId) {
            base.Channel.startGame(hostUsername, lobbyId);
        }
        
        public System.Threading.Tasks.Task startGameAsync(string hostUsername, string lobbyId) {
            return base.Channel.startGameAsync(hostUsername, lobbyId);
        }
        
        public void kickPlayer(string hostUsername, string playerToKickUsername, string lobbyId) {
            base.Channel.kickPlayer(hostUsername, playerToKickUsername, lobbyId);
        }
        
        public System.Threading.Tasks.Task kickPlayerAsync(string hostUsername, string playerToKickUsername, string lobbyId) {
            return base.Channel.kickPlayerAsync(hostUsername, playerToKickUsername, lobbyId);
        }
        
        public void changeDifficulty(string hostUsername, string lobbyId, int newDifficultyId) {
            base.Channel.changeDifficulty(hostUsername, lobbyId, newDifficultyId);
        }
        
        public System.Threading.Tasks.Task changeDifficultyAsync(string hostUsername, string lobbyId, int newDifficultyId) {
            return base.Channel.changeDifficultyAsync(hostUsername, lobbyId, newDifficultyId);
        }
        
        public void inviteGuestByEmail(MindWeaveClient.MatchmakingService.GuestInvitationDto invitationData) {
            base.Channel.inviteGuestByEmail(invitationData);
        }
        
        public System.Threading.Tasks.Task inviteGuestByEmailAsync(MindWeaveClient.MatchmakingService.GuestInvitationDto invitationData) {
            return base.Channel.inviteGuestByEmailAsync(invitationData);
        }
        
        public MindWeaveClient.MatchmakingService.GuestJoinResultDto joinLobbyAsGuest(MindWeaveClient.MatchmakingService.GuestJoinRequestDto joinRequest) {
            return base.Channel.joinLobbyAsGuest(joinRequest);
        }
        
        public System.Threading.Tasks.Task<MindWeaveClient.MatchmakingService.GuestJoinResultDto> joinLobbyAsGuestAsync(MindWeaveClient.MatchmakingService.GuestJoinRequestDto joinRequest) {
            return base.Channel.joinLobbyAsGuestAsync(joinRequest);
        }
        
        public void requestPieceDrag(string lobbyCode, int pieceId) {
            base.Channel.requestPieceDrag(lobbyCode, pieceId);
        }
        
        public System.Threading.Tasks.Task requestPieceDragAsync(string lobbyCode, int pieceId) {
            return base.Channel.requestPieceDragAsync(lobbyCode, pieceId);
        }
        
        public void requestPieceMove(string lobbyCode, int pieceId, double newX, double newY) {
            base.Channel.requestPieceMove(lobbyCode, pieceId, newX, newY);
        }
        
        public System.Threading.Tasks.Task requestPieceMoveAsync(string lobbyCode, int pieceId, double newX, double newY) {
            return base.Channel.requestPieceMoveAsync(lobbyCode, pieceId, newX, newY);
        }
        
        public void requestPieceDrop(string lobbyCode, int pieceId, double newX, double newY) {
            base.Channel.requestPieceDrop(lobbyCode, pieceId, newX, newY);
        }
        
        public System.Threading.Tasks.Task requestPieceDropAsync(string lobbyCode, int pieceId, double newX, double newY) {
            return base.Channel.requestPieceDropAsync(lobbyCode, pieceId, newX, newY);
        }
        
        public void requestPieceRelease(string lobbyCode, int pieceId) {
            base.Channel.requestPieceRelease(lobbyCode, pieceId);
        }
        
        public System.Threading.Tasks.Task requestPieceReleaseAsync(string lobbyCode, int pieceId) {
            return base.Channel.requestPieceReleaseAsync(lobbyCode, pieceId);
        }
    }
}
