//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveClient.MatchmakingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbySettingsDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class LobbySettingsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] customPuzzleImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int difficultyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> preloadedPuzzleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] customPuzzleImage {
            get {
                return this.customPuzzleImageField;
            }
            set {
                if ((object.ReferenceEquals(this.customPuzzleImageField, value) != true)) {
                    this.customPuzzleImageField = value;
                    this.RaisePropertyChanged("customPuzzleImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int difficultyId {
            get {
                return this.difficultyIdField;
            }
            set {
                if ((this.difficultyIdField.Equals(value) != true)) {
                    this.difficultyIdField = value;
                    this.RaisePropertyChanged("difficultyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> preloadedPuzzleId {
            get {
                return this.preloadedPuzzleIdField;
            }
            set {
                if ((this.preloadedPuzzleIdField.Equals(value) != true)) {
                    this.preloadedPuzzleIdField = value;
                    this.RaisePropertyChanged("preloadedPuzzleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.S" +
        "hared")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MindWeaveClient.MatchmakingService.GuestJoinResultDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MindWeaveClient.MatchmakingService.LobbyCreationResultDto))]
    public partial class OperationResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestJoinResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class GuestJoinResultDto : MindWeaveClient.MatchmakingService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string assignedGuestUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.LobbyStateDto initialLobbyStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string assignedGuestUsername {
            get {
                return this.assignedGuestUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.assignedGuestUsernameField, value) != true)) {
                    this.assignedGuestUsernameField = value;
                    this.RaisePropertyChanged("assignedGuestUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.LobbyStateDto initialLobbyState {
            get {
                return this.initialLobbyStateField;
            }
            set {
                if ((object.ReferenceEquals(this.initialLobbyStateField, value) != true)) {
                    this.initialLobbyStateField = value;
                    this.RaisePropertyChanged("initialLobbyState");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyCreationResultDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class LobbyCreationResultDto : MindWeaveClient.MatchmakingService.OperationResultDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.LobbyStateDto initialLobbyStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lobbyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.LobbyStateDto initialLobbyState {
            get {
                return this.initialLobbyStateField;
            }
            set {
                if ((object.ReferenceEquals(this.initialLobbyStateField, value) != true)) {
                    this.initialLobbyStateField = value;
                    this.RaisePropertyChanged("initialLobbyState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lobbyCode {
            get {
                return this.lobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.lobbyCodeField, value) != true)) {
                    this.lobbyCodeField = value;
                    this.RaisePropertyChanged("lobbyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyStateDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class LobbyStateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.LobbySettingsDto currentSettingsDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hostUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lobbyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] playersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string puzzleImagePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.LobbySettingsDto currentSettingsDto {
            get {
                return this.currentSettingsDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.currentSettingsDtoField, value) != true)) {
                    this.currentSettingsDtoField = value;
                    this.RaisePropertyChanged("currentSettingsDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hostUsername {
            get {
                return this.hostUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.hostUsernameField, value) != true)) {
                    this.hostUsernameField = value;
                    this.RaisePropertyChanged("hostUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lobbyId {
            get {
                return this.lobbyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.lobbyIdField, value) != true)) {
                    this.lobbyIdField = value;
                    this.RaisePropertyChanged("lobbyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] players {
            get {
                return this.playersField;
            }
            set {
                if ((object.ReferenceEquals(this.playersField, value) != true)) {
                    this.playersField = value;
                    this.RaisePropertyChanged("players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string puzzleImagePath {
            get {
                return this.puzzleImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.puzzleImagePathField, value) != true)) {
                    this.puzzleImagePathField = value;
                    this.RaisePropertyChanged("puzzleImagePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestInvitationDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class GuestInvitationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guestEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string inviterUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lobbyCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guestEmail {
            get {
                return this.guestEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.guestEmailField, value) != true)) {
                    this.guestEmailField = value;
                    this.RaisePropertyChanged("guestEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inviterUsername {
            get {
                return this.inviterUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.inviterUsernameField, value) != true)) {
                    this.inviterUsernameField = value;
                    this.RaisePropertyChanged("inviterUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lobbyCode {
            get {
                return this.lobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.lobbyCodeField, value) != true)) {
                    this.lobbyCodeField = value;
                    this.RaisePropertyChanged("lobbyCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestJoinRequestDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.M" +
        "atchmaking")]
    [System.SerializableAttribute()]
    public partial class GuestJoinRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desiredGuestUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guestEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lobbyCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desiredGuestUsername {
            get {
                return this.desiredGuestUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.desiredGuestUsernameField, value) != true)) {
                    this.desiredGuestUsernameField = value;
                    this.RaisePropertyChanged("desiredGuestUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guestEmail {
            get {
                return this.guestEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.guestEmailField, value) != true)) {
                    this.guestEmailField = value;
                    this.RaisePropertyChanged("guestEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lobbyCode {
            get {
                return this.lobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.lobbyCodeField, value) != true)) {
                    this.lobbyCodeField = value;
                    this.RaisePropertyChanged("lobbyCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuzzleDefinitionDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.P" +
        "uzzle")]
    [System.SerializableAttribute()]
    public partial class PuzzleDefinitionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fullImageBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MindWeaveClient.MatchmakingService.PuzzlePieceDefinitionDto[] piecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puzzleHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puzzleWidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] fullImageBytes {
            get {
                return this.fullImageBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.fullImageBytesField, value) != true)) {
                    this.fullImageBytesField = value;
                    this.RaisePropertyChanged("fullImageBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MindWeaveClient.MatchmakingService.PuzzlePieceDefinitionDto[] pieces {
            get {
                return this.piecesField;
            }
            set {
                if ((object.ReferenceEquals(this.piecesField, value) != true)) {
                    this.piecesField = value;
                    this.RaisePropertyChanged("pieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puzzleHeight {
            get {
                return this.puzzleHeightField;
            }
            set {
                if ((this.puzzleHeightField.Equals(value) != true)) {
                    this.puzzleHeightField = value;
                    this.RaisePropertyChanged("puzzleHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puzzleWidth {
            get {
                return this.puzzleWidthField;
            }
            set {
                if ((this.puzzleWidthField.Equals(value) != true)) {
                    this.puzzleWidthField = value;
                    this.RaisePropertyChanged("puzzleWidth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuzzlePieceDefinitionDto", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.P" +
        "uzzle")]
    [System.SerializableAttribute()]
    public partial class PuzzlePieceDefinitionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double correctXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double correctYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int heightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pieceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sourceXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sourceYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int widthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double correctX {
            get {
                return this.correctXField;
            }
            set {
                if ((this.correctXField.Equals(value) != true)) {
                    this.correctXField = value;
                    this.RaisePropertyChanged("correctX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double correctY {
            get {
                return this.correctYField;
            }
            set {
                if ((this.correctYField.Equals(value) != true)) {
                    this.correctYField = value;
                    this.RaisePropertyChanged("correctY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int height {
            get {
                return this.heightField;
            }
            set {
                if ((this.heightField.Equals(value) != true)) {
                    this.heightField = value;
                    this.RaisePropertyChanged("height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pieceId {
            get {
                return this.pieceIdField;
            }
            set {
                if ((this.pieceIdField.Equals(value) != true)) {
                    this.pieceIdField = value;
                    this.RaisePropertyChanged("pieceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sourceX {
            get {
                return this.sourceXField;
            }
            set {
                if ((this.sourceXField.Equals(value) != true)) {
                    this.sourceXField = value;
                    this.RaisePropertyChanged("sourceX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sourceY {
            get {
                return this.sourceYField;
            }
            set {
                if ((this.sourceYField.Equals(value) != true)) {
                    this.sourceYField = value;
                    this.RaisePropertyChanged("sourceY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int width {
            get {
                return this.widthField;
            }
            set {
                if ((this.widthField.Equals(value) != true)) {
                    this.widthField = value;
                    this.RaisePropertyChanged("width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchmakingService.IMatchmakingManager", CallbackContract=typeof(MindWeaveClient.MatchmakingService.IMatchmakingManagerCallback))]
    public interface IMatchmakingManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/createLobby", ReplyAction="http://tempuri.org/IMatchmakingManager/createLobbyResponse")]
        MindWeaveClient.MatchmakingService.LobbyCreationResultDto createLobby(string hostUsername, MindWeaveClient.MatchmakingService.LobbySettingsDto settingsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/createLobby", ReplyAction="http://tempuri.org/IMatchmakingManager/createLobbyResponse")]
        System.Threading.Tasks.Task<MindWeaveClient.MatchmakingService.LobbyCreationResultDto> createLobbyAsync(string hostUsername, MindWeaveClient.MatchmakingService.LobbySettingsDto settingsDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/inviteToLobby")]
        void inviteToLobby(string inviterUsername, string invitedUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/inviteToLobby")]
        System.Threading.Tasks.Task inviteToLobbyAsync(string inviterUsername, string invitedUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/joinLobby")]
        void joinLobby(string username, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/joinLobby")]
        System.Threading.Tasks.Task joinLobbyAsync(string username, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/leaveLobby")]
        void leaveLobby(string username, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/leaveLobby")]
        System.Threading.Tasks.Task leaveLobbyAsync(string username, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/startGame")]
        void startGame(string hostUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/startGame")]
        System.Threading.Tasks.Task startGameAsync(string hostUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/kickPlayer")]
        void kickPlayer(string hostUsername, string playerToKickUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/kickPlayer")]
        System.Threading.Tasks.Task kickPlayerAsync(string hostUsername, string playerToKickUsername, string lobbyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/changeDifficulty")]
        void changeDifficulty(string hostUsername, string lobbyId, int newDifficultyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/changeDifficulty")]
        System.Threading.Tasks.Task changeDifficultyAsync(string hostUsername, string lobbyId, int newDifficultyId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/inviteGuestByEmail")]
        void inviteGuestByEmail(MindWeaveClient.MatchmakingService.GuestInvitationDto invitationData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/inviteGuestByEmail")]
        System.Threading.Tasks.Task inviteGuestByEmailAsync(MindWeaveClient.MatchmakingService.GuestInvitationDto invitationData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuest", ReplyAction="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuestResponse")]
        MindWeaveClient.MatchmakingService.GuestJoinResultDto joinLobbyAsGuest(MindWeaveClient.MatchmakingService.GuestJoinRequestDto joinRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuest", ReplyAction="http://tempuri.org/IMatchmakingManager/joinLobbyAsGuestResponse")]
        System.Threading.Tasks.Task<MindWeaveClient.MatchmakingService.GuestJoinResultDto> joinLobbyAsGuestAsync(MindWeaveClient.MatchmakingService.GuestJoinRequestDto joinRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/sendPiecePlaced", ReplyAction="http://tempuri.org/IMatchmakingManager/sendPiecePlacedResponse")]
        void sendPiecePlaced(int pieceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/sendPiecePlaced", ReplyAction="http://tempuri.org/IMatchmakingManager/sendPiecePlacedResponse")]
        System.Threading.Tasks.Task sendPiecePlacedAsync(int pieceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/updateLobbyState")]
        void updateLobbyState(MindWeaveClient.MatchmakingService.LobbyStateDto lobbyStateDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/matchFound")]
        void matchFound(string matchId, string[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/lobbyCreationFailed")]
        void lobbyCreationFailed(string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/kickedFromLobby")]
        void kickedFromLobby(string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/onGameStarted")]
        void onGameStarted(MindWeaveClient.MatchmakingService.PuzzleDefinitionDto puzzleDefinition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerChannel : MindWeaveClient.MatchmakingService.IMatchmakingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchmakingManagerClient : System.ServiceModel.DuplexClientBase<MindWeaveClient.MatchmakingService.IMatchmakingManager>, MindWeaveClient.MatchmakingService.IMatchmakingManager {
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public MindWeaveClient.MatchmakingService.LobbyCreationResultDto createLobby(string hostUsername, MindWeaveClient.MatchmakingService.LobbySettingsDto settingsDto) {
            return base.Channel.createLobby(hostUsername, settingsDto);
        }
        
        public System.Threading.Tasks.Task<MindWeaveClient.MatchmakingService.LobbyCreationResultDto> createLobbyAsync(string hostUsername, MindWeaveClient.MatchmakingService.LobbySettingsDto settingsDto) {
            return base.Channel.createLobbyAsync(hostUsername, settingsDto);
        }
        
        public void inviteToLobby(string inviterUsername, string invitedUsername, string lobbyId) {
            base.Channel.inviteToLobby(inviterUsername, invitedUsername, lobbyId);
        }
        
        public System.Threading.Tasks.Task inviteToLobbyAsync(string inviterUsername, string invitedUsername, string lobbyId) {
            return base.Channel.inviteToLobbyAsync(inviterUsername, invitedUsername, lobbyId);
        }
        
        public void joinLobby(string username, string lobbyId) {
            base.Channel.joinLobby(username, lobbyId);
        }
        
        public System.Threading.Tasks.Task joinLobbyAsync(string username, string lobbyId) {
            return base.Channel.joinLobbyAsync(username, lobbyId);
        }
        
        public void leaveLobby(string username, string lobbyId) {
            base.Channel.leaveLobby(username, lobbyId);
        }
        
        public System.Threading.Tasks.Task leaveLobbyAsync(string username, string lobbyId) {
            return base.Channel.leaveLobbyAsync(username, lobbyId);
        }
        
        public void startGame(string hostUsername, string lobbyId) {
            base.Channel.startGame(hostUsername, lobbyId);
        }
        
        public System.Threading.Tasks.Task startGameAsync(string hostUsername, string lobbyId) {
            return base.Channel.startGameAsync(hostUsername, lobbyId);
        }
        
        public void kickPlayer(string hostUsername, string playerToKickUsername, string lobbyId) {
            base.Channel.kickPlayer(hostUsername, playerToKickUsername, lobbyId);
        }
        
        public System.Threading.Tasks.Task kickPlayerAsync(string hostUsername, string playerToKickUsername, string lobbyId) {
            return base.Channel.kickPlayerAsync(hostUsername, playerToKickUsername, lobbyId);
        }
        
        public void changeDifficulty(string hostUsername, string lobbyId, int newDifficultyId) {
            base.Channel.changeDifficulty(hostUsername, lobbyId, newDifficultyId);
        }
        
        public System.Threading.Tasks.Task changeDifficultyAsync(string hostUsername, string lobbyId, int newDifficultyId) {
            return base.Channel.changeDifficultyAsync(hostUsername, lobbyId, newDifficultyId);
        }
        
        public void inviteGuestByEmail(MindWeaveClient.MatchmakingService.GuestInvitationDto invitationData) {
            base.Channel.inviteGuestByEmail(invitationData);
        }
        
        public System.Threading.Tasks.Task inviteGuestByEmailAsync(MindWeaveClient.MatchmakingService.GuestInvitationDto invitationData) {
            return base.Channel.inviteGuestByEmailAsync(invitationData);
        }
        
        public MindWeaveClient.MatchmakingService.GuestJoinResultDto joinLobbyAsGuest(MindWeaveClient.MatchmakingService.GuestJoinRequestDto joinRequest) {
            return base.Channel.joinLobbyAsGuest(joinRequest);
        }
        
        public System.Threading.Tasks.Task<MindWeaveClient.MatchmakingService.GuestJoinResultDto> joinLobbyAsGuestAsync(MindWeaveClient.MatchmakingService.GuestJoinRequestDto joinRequest) {
            return base.Channel.joinLobbyAsGuestAsync(joinRequest);
        }
        
        public void sendPiecePlaced(int pieceId) {
            base.Channel.sendPiecePlaced(pieceId);
        }
        
        public System.Threading.Tasks.Task sendPiecePlacedAsync(int pieceId) {
            return base.Channel.sendPiecePlacedAsync(pieceId);
        }
    }
}
