//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveClient.HeartbeatService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeartbeatRegistrationResult", Namespace="http://schemas.datacontract.org/2004/07/MindWeaveServer.Contracts.DataContracts.H" +
        "eartbeat")]
    [System.SerializableAttribute()]
    public partial class HeartbeatRegistrationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeartbeatIntervalMsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeoutMsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HeartbeatIntervalMs {
            get {
                return this.HeartbeatIntervalMsField;
            }
            set {
                if ((this.HeartbeatIntervalMsField.Equals(value) != true)) {
                    this.HeartbeatIntervalMsField = value;
                    this.RaisePropertyChanged("HeartbeatIntervalMs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeoutMs {
            get {
                return this.TimeoutMsField;
            }
            set {
                if ((this.TimeoutMsField.Equals(value) != true)) {
                    this.TimeoutMsField = value;
                    this.RaisePropertyChanged("TimeoutMs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HeartbeatService.IHeartbeatManager", CallbackContract=typeof(MindWeaveClient.HeartbeatService.IHeartbeatManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IHeartbeatManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeartbeatManager/registerForHeartbeat", ReplyAction="http://tempuri.org/IHeartbeatManager/registerForHeartbeatResponse")]
        MindWeaveClient.HeartbeatService.HeartbeatRegistrationResult registerForHeartbeat(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeartbeatManager/registerForHeartbeat", ReplyAction="http://tempuri.org/IHeartbeatManager/registerForHeartbeatResponse")]
        System.Threading.Tasks.Task<MindWeaveClient.HeartbeatService.HeartbeatRegistrationResult> registerForHeartbeatAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHeartbeatManager/sendHeartbeat")]
        void sendHeartbeat(string username, long sequenceNumber, long clientTimestamp);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHeartbeatManager/sendHeartbeat")]
        System.Threading.Tasks.Task sendHeartbeatAsync(string username, long sequenceNumber, long clientTimestamp);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHeartbeatManager/unregisterHeartbeat")]
        void unregisterHeartbeat(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHeartbeatManager/unregisterHeartbeat")]
        System.Threading.Tasks.Task unregisterHeartbeatAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeartbeatManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHeartbeatManager/heartbeatAck")]
        void heartbeatAck(long sequenceNumber, long serverTimestamp);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHeartbeatManager/connectionTerminating")]
        void connectionTerminating(string reason);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeartbeatManagerChannel : MindWeaveClient.HeartbeatService.IHeartbeatManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeartbeatManagerClient : System.ServiceModel.DuplexClientBase<MindWeaveClient.HeartbeatService.IHeartbeatManager>, MindWeaveClient.HeartbeatService.IHeartbeatManager {
        
        public HeartbeatManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public HeartbeatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public HeartbeatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public HeartbeatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public HeartbeatManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public MindWeaveClient.HeartbeatService.HeartbeatRegistrationResult registerForHeartbeat(string username) {
            return base.Channel.registerForHeartbeat(username);
        }
        
        public System.Threading.Tasks.Task<MindWeaveClient.HeartbeatService.HeartbeatRegistrationResult> registerForHeartbeatAsync(string username) {
            return base.Channel.registerForHeartbeatAsync(username);
        }
        
        public void sendHeartbeat(string username, long sequenceNumber, long clientTimestamp) {
            base.Channel.sendHeartbeat(username, sequenceNumber, clientTimestamp);
        }
        
        public System.Threading.Tasks.Task sendHeartbeatAsync(string username, long sequenceNumber, long clientTimestamp) {
            return base.Channel.sendHeartbeatAsync(username, sequenceNumber, clientTimestamp);
        }
        
        public void unregisterHeartbeat(string username) {
            base.Channel.unregisterHeartbeat(username);
        }
        
        public System.Threading.Tasks.Task unregisterHeartbeatAsync(string username) {
            return base.Channel.unregisterHeartbeatAsync(username);
        }
    }
}
