// MindWeaveClient/Services/ChatCallbackHandler.cs
using MindWeaveClient.ChatManagerService; // Use the namespace generated by the service reference
using System;
using System.Diagnostics;
using System.Windows; // For Application.Current.Dispatcher

namespace MindWeaveClient.Services
{
    public class ChatCallbackHandler : IChatManagerCallback // Interface generated by service reference
    {
        public event Action<ChatMessageDto> LobbyMessageReceived;

        public void receiveLobbyMessage(ChatMessageDto messageDto)
        {
            Debug.WriteLine($"---> Chat Callback: Message received from {messageDto.senderUsername}: '{messageDto.content}'");
            // Use Dispatcher to invoke the event on the UI thread
            Application.Current?.Dispatcher?.Invoke(() =>
            {
                LobbyMessageReceived?.Invoke(messageDto);
            });
        }

        // Implement other methods from IChatCallback if you add them later (e.g., userJoinedChat)
    }
}